name: breakable-block
version: "1.0-SNAPSHOT"
author: Your Name
main: fr.yohem.MyPlugin
commands:
    block-breakable:
      usage: "/block-breakable timeInSecToRegen idRecomp:data min-maxQuantity idBlockAfterBreak:data"
      description: set block breakable 
      permission: breakable-bloc.set
    no-block-breakable:
      usage: "/no-block-breakable"
      description: unset block breakable 
      permission: breakable-bloc.set
permissions:
  breakable-bloc.use :
    default: true
  breakable-bloc.set :
    default: true
